# App
spring.application.name=notification-platform

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/notification_platform
spring.datasource.username=root
spring.datasource.password=Vigkul2004*
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=buildproject55@gmail.com
spring.mail.password=zguvyuvpqoxrkmqv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App custom
app.jwt.secret=your-secret-key-here-make-it-long
app.free.plan.limit=1000

app.sms.api.key=r6wdhjXDq0VngKWG2xNOQMRCUYAvBaPc4T3Ez8t5yilfupm7bF35Z1kBH2ds8xLgJPXAcbUa6QReltim

app.admin.username=admin
app.admin.password=admin123

springdoc.api-docs.enabled=true
spring.mvc.pathmatch.use-suffix-pattern=false

springdoc.packagesToScan=com.vivek.notification.notification_platform.controller
springdoc.pathsToMatch=/api/**